using Microsoft.AspNetCore.Mvc;
using ProductCatalogService.Business.Interfaces;

namespace ProductCatalogService.API.Controllers
{
    //Generated by ChatGPT o1-preview
    [ApiController]
    [Route("api/[controller]")]
    public class ProductController : ControllerBase
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var products = _productService.GetProducts();
            return Ok(products);
        }
    }
}